#!/bin/sh
# Author: Kamil Cukrowski
# License: Jointly under MIT License and Beerware license

archivetmpfs_mount_handler_2=""

archivetmpfs_mount_handler_err() {
   echo "You are now being dropped into an emergency shell."
   launch_interactive_shell
}

archivetmpfs_mount_handler() {
   local dest path
   dest="$1"
   path="$archivetmpfs"

   msg "Mounting tmpfs to '$dest'"
   if ! mount -t tmpfs -o size=100% none "$dest"; then
      err "Error mounting tmpfs to '$dest'"
      archivetmpfs_mount_handler_err
   fi

   case "$path" in
   /*)
      # local path inside mount_handler mounted directory
      local temproot
      temproot="/temp_root"
      msg "Mounting root to '$temproot'"
      mkdir -p "$temproot"
      "$archivetmpfs_mount_handler_2" "$temproot"

      local apath
      apath="${temproot}/${path}"
      if [ -d "$apath" ]; then
         msg "Found directory '$path'."
         msg "Copying directory content into tmpfs dir."
         if ! cp -rfa "$apath"/* "$dest"; then
            err "Error copying '$path' into '$dest' tmpfs dir."
            msg "Leaving filesystem mounted in $temproot"
            archivetmpfs_mount_handler_err
         fi
      elif [ -f "$apath" ]; then
         msg "Found file '$path'."
         msg "Uncompressing archive to tmpfs dir."
         if ! tar -axf "$apath" -C "$dest"; then
            err "Error uncompressing the archive '$path' into '$dest' tmpfs dir."
            msg "Leaving filesystem mounted in $temproot"
            archivetmpfs_mount_handler_err
         fi
      else
         err "Path '$path' not found inside '$temproot' root device."
         msg "Leaving filesystem mounted in $temproot"
         archivetmpfs_mount_handler_err
      fi

      msg "Unmoount"
      umount "$temproot"
      ;;
   https://*|http://*|ftp://*)
      # url link - download using curl, unpack using tar
      local out
      out="$1/$(basename "$path")"
      msg "Downloading file '$path' to '$out'"
      if ! curl -O "$out" "$path"; then
         err "Error downloading"
         archivetmpfs_mount_handler_err
      fi
      msg "Uncompressing downloaded file '$out' file to tmpfs dir."
      if ! tar -axf "$out" -C "$dest"; then
        err "Error in uncompressing the archive"
        archivetmpfs_mount_handler_err
      fi
      ;;
   *)
      err "Unknown path '$path'"
      archivetmpfs_mount_handler_err
      ;;
   esac
}

run_hook() {
   if [ -n "${archivetmpfs}" ]; then
      archivetmpfs_mount_handler_2="${mount_handler}"
      mount_handler="archivetmpfs_mount_handler"
   fi
}
