#!/bin/bash
# Author: Kamil Cukrowski
# License: Jointly under MIT License and Beerware license

build() {
    map add_binary tar gzip
    add_runscript
}

help() {
    cat <<MESSAGE
This hooks allows copying whole chroot to tmppfs and boot to it.

Command Line Setup:

    Set root=... to where Your chroot is.
    Use specific hook (or no hook at all) to mount Your root.
    Set archivetmpfs=... to a path to a directory or file within Your root containing chroot.
    This chroot will be copied to tmpfs and from that tmpfs the boot process will continue.
    This hook will copy whole chroot to tmpfs mounted directory.
    Then the boot process will continue from the tmpfs.
    When omitting archivetmpfs boot command line parameter, will make booting as usual from a root=... device.

    Supported archivetmpfs parameters:
        - directory
            Will copy all the files from directory into tmpfs dir.
            archivetmpfs=/root/mychroot
        - Tar archive file
            Will use command 'tar -a' to unpack the archive into tmpfs dir.
            archivetmpfs=/root/mychroot.tar
        TODO:
        - url link
            Will download the url link and then use 'tar -a' to unpack the file into tmpfs dir.
            archivetmpfs=http://site.net/file.tar.bz2
            archivetmpfs=ftp://site.net/file.tar.gz
    
MESSAGE
}
